spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/lxn?characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
      username: root
      password: Root@123